Hand Written Digit Prediction

Import Library

In [49]:
import pandas as pd

In [50]:
import numpy as np

In [51]:
import matplotlib.pyplot as plt

Import Data

In [52]:
from sklearn.datasets import load_digits

In [53]:
Sh=load_digits()

Data Preprocessing

In [54]:
Sh.images.shape

(1797, 8, 8)

In [55]:
Sh.images[0]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [56]:
len(Sh.images)

1797

In [57]:
n_samples=len(Sh.images)
data=Sh.images.reshape((n_samples,-1))

In [58]:
data [0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [59]:
data[0].shape

(64,)

In [60]:
data.shape

(1797, 64)

Scaling Image Data

In [61]:
data.min()

0.0

In [62]:
data.max()

16.0

In [63]:
data=data/16

In [64]:
data.min()

0.0

In [65]:
data.max()

1.0

In [66]:
data [0]

array([0.    , 0.    , 0.3125, 0.8125, 0.5625, 0.0625, 0.    , 0.    ,
       0.    , 0.    , 0.8125, 0.9375, 0.625 , 0.9375, 0.3125, 0.    ,
       0.    , 0.1875, 0.9375, 0.125 , 0.    , 0.6875, 0.5   , 0.    ,
       0.    , 0.25  , 0.75  , 0.    , 0.    , 0.5   , 0.5   , 0.    ,
       0.    , 0.3125, 0.5   , 0.    , 0.    , 0.5625, 0.5   , 0.    ,
       0.    , 0.25  , 0.6875, 0.    , 0.0625, 0.75  , 0.4375, 0.    ,
       0.    , 0.125 , 0.875 , 0.3125, 0.625 , 0.75  , 0.    , 0.    ,
       0.    , 0.    , 0.375 , 0.8125, 0.625 , 0.    , 0.    , 0.    ])

Train Test Split Data

In [67]:
from sklearn.model_selection import train_test_split

In [68]:
x_train,x_test,y_train,y_test = train_test_split(data,Sh.target, test_size=0.7,random_state=222529)

In [69]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((539, 64), (1258, 64), (539,), (1258,))

Random Forest Model

In [70]:

from sklearn.ensemble import RandomForestClassifier

In [71]:
pf=RandomForestClassifier()

In [72]:
pf.fit(x_train,y_train)

RandomForestClassifier()

Predict Test Data

In [73]:
Y_pred = pf.predict(x_test)

In [74]:
Y_pred

array([9, 0, 4, ..., 9, 2, 0])

Model Acuracy

In [75]:

from sklearn.metrics import confusion_matrix, classification_report

In [76]:
confusion_matrix(y_test,y_pred)

array([[123,   0,   0,   0,   2,   0,   0,   0,   0,   0],
       [  0, 125,   0,   0,   0,   0,   0,   0,   0,   0],
       [  1,   6, 118,   0,   0,   0,   0,   0,   1,   0],
       [  0,   0,   1, 117,   0,   0,   0,   1,   8,   0],
       [  0,   2,   0,   0, 119,   0,   0,   3,   0,   1],
       [  0,   0,   0,   0,   1, 123,   1,   0,   0,   0],
       [  1,   3,   0,   0,   1,   0, 126,   0,   0,   0],
       [  0,   0,   0,   0,   1,   0,   0, 115,   1,   1],
       [  0,   7,   1,   2,   1,   1,   0,   0, 115,   0],
       [  0,   3,   0,   3,   0,   1,   0,   1,   5, 116]])

In [77]:
print(classification_report(y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       125
           1       0.87      1.00      0.93       125
           2       0.97      0.93      0.95       126
           3       0.97      0.92      0.94       127
           4       0.95      0.97      0.96       125
           5       0.98      0.97      0.98       125
           6       1.00      0.98      0.99       131
           7       0.93      0.97      0.95       118
           8       0.90      0.90      0.90       127
           9       0.97      0.90      0.93       129

    accuracy                           0.95      1258
   macro avg       0.95      0.95      0.95      1258
weighted avg       0.95      0.95      0.95      1258

